---
# tasks file for uploadimage
- name: Upload image files to S3 bucket
  aws_s3:
    bucket: "{{ s3_bucket_name }}"
    mode: put
    object: "{{ s3_destination_folder }}/{{ image }}"
    src: "{{ local_image_directory }}/{{ image }}"
  with_fileglob:
        - "{{ local_image_directory }}/{{ image }}"
