---
- name: Upload image files to S3 bucket
  amazon.aws.s3_object:
    bucket: "{{ uploadimage_s3_bucket_name }}"
    mode: put
    object: "{{ uploadimage_image }}"
    src: "{{ uploadimage_local_image_directory }}/{{ uploadimage_image }}"
  with_fileglob:
    - "{{ uploadimage_local_image_directory }}/{{ uploadimage_image }}"
