---
# tasks file for uploadimage
- name: Upload image files to S3 bucket
  amazon.aws.aws_s3:
     # ansible-lint: ignore=AWS306
    bucket: "{{ s3_bucket_name }}"
    mode: put
    object: "{{ image }}"
    src: "{{ local_image_directory }}/{{ image }}"
  with_fileglob:
        - "{{ local_image_directory }}/{{ image }}"
