---
# tasks file for installweb
- name: Update package cache and install httpd
  become: true
  package:
    name: httpd

- name: Start httpd service and enable it on boot
  become: true
  service:
    name: httpd
    state: started
    enabled: true
  notify: restart httpd

- name: Create webpage fetching image from S3
  become: true
  template:
    src: templates/webpage.j2
    dest: "{{ web_root }}/{{ webpage_file }}"
    
  vars:
    s3_bucket: "{{ s3_bucket_name }}"
    s3_image: "{{ s3_image_key }}"
