---
# tasks file for installweb
- name: Update package cache and install httpd
  become: true
  ansible.builtin.package:
    name: httpd

- name: Start httpd service and enable it on boot
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  notify: restart httpd

- name: Create webpage fetching image from S3
  become: true
  ansible.builtin.template:
    src: templates/webpage.j2
    dest: "{{ installweb_web_root }}/{{ installweb_webpage_file }}"
  vars:
    s3_bucket: "{{ installweb_s3_bucket_name }}"
    s3_image: "{{ installweb_s3_image_key }}"
