- name: Upload images to S3 bucket
  hosts: localhost
  vars_files:
    - ./vars/variable.yml
  roles:
    - uploadimage

- name: Install httpd on webserver group
  hosts: tag_webserver
  gather_facts: true
  vars_files:
    - ./vars/variable.yml
  roles:
    - installweb
