- name: Upload images to S3 bucket
  hosts: localhost
  
  tasks:
    - name: upload image to S3 role
      include_role:
        name: uploadimage

   
- name: Install httpd on webserver group
  hosts: tag_webserver
  gather_facts: true

  tasks:
    - name: install httpd and create webpage role
      include_role:
        name: installweb
