# - name: Upload images to S3 bucket
#   hosts: localhost
#   roles:
#     - uploadimage

- name: Install httpd on webserver group
  hosts: tag_webserver
  gather_facts: true
  vars_files:
    - ./group_vars/tag_webserver
  roles:
    - installweb
